### ISSUE TITLE
freeling-engine fail to start even test case fails due to UnsatisfiedLinkError

### ISSUE THREAD

**Issue by mido18** [insideout10/wordlift-stanbol#3]
This what i get from running tests 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.055 sec <<< FAILURE!
test(io.insideout.wordlift.org.apache.stanbol.enhancer.engines.freeling.TestLanguageIdentifier)  Time elapsed: 0.024 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: edu.upc.freeling.freelingJNI.new_LangIdent(Ljava/lang/String;)J
    at edu.upc.freeling.freelingJNI.new_LangIdent(Native Method)
    at edu.upc.freeling.LangIdent.<init>(LangIdent.java:39)
    at io.insideout.wordlift.org.apache.stanbol.enhancer.engines.freeling.impl.LanguageIdentifierImpl.<init>(LanguageIdentifierImpl.java:51)
    at io.insideout.wordlift.org.apache.stanbol.enhancer.engines.freeling.TestLanguageIdentifier.test(TestLanguageIdentifier.java:34)

i am sure that libfreeling_javaAPI.so is a shared resource at my system i searched pom.xml i found this 
<Bundle-NativeCode>
                            libfreeling_javaAPI.jnilib;osname=MacOSX;processor=x86-64,
</Bundle-NativeCode>

i tried to change it to that

<Bundle-NativeCode>
    libfreeling_javaAPI.jnilib;osname=MacOSX;processor=x86-64,
    libfreeling_javaAPI.jnilib;osname=Linux;processor=x86-64,
    libfreeling_javaAPI.so;osname=Linux;processor=x86-64
</Bundle-NativeCode>

i copied libfreeling_javaApi.so to src/main/resources - src/test/resources but i also get the same error 
i copied also libfreeling_javaAPI.jnilib to usr/lib but it's also same so i can't figure where the problem is

**Comment by ziodave** [comment]
The issue _UnsatisfiedLinkError_ arises because the native library is not found: you're required to configure the correct location of you libfreeling_javaAPI library.

Please check here, OSGi Documentation http://www.osgi.org/Download/Release4V43, at page 60 **3.10 Loading Native Code Libraries** how to correctly configure the bundle.

Check for the correct naming of properties at page 100 **4.5.3 Environment Properties** with particular regards to the _osname_ and _processor_ values.

Last but not least, copy the library in the following folder of your local project copy:

``` sh
freeling-engine/src/main/resources/lib
```

Please don't remove the MacOSX definition, add the Linux one so that, once successful, we can pull back the update.

**Comment by ziodave** [comment]
One more thing, in the stack trace I can see that a test is failing.

Tests aren't running in the OSGi context therefore the bundle configuration won't apply.

You need to uncomment the line loading the support library in the source file and point it to your local copy of the library (https://github.com/insideout10/wordlift-stanbol/blob/master/freeling-engine/src/test/java/io/insideout/wordlift/org/apache/stanbol/enhancer/engines/freeling/TestLanguageIdentifier.java).

**Comment by mido18** [comment]
i can't find FreelingSupportLibrary class in package edu.upc.freeling or in package io.insideout.wordlift.org.apache.stanbol.enhancer.engines.freeling ?!

**Comment by ziodave** [comment]
It doesn't exist anymore. You can load a library using one of the following two methods:
- System.load: http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/System.html#load(java.lang.String)
- System.loadLibrary: http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/System.html#loadLibrary(java.lang.String)

**Comment by mido18** [comment]
System.load("/usr/local/lib/libfreeling_javaAPI.so"); is working in class TestPartOfSpeachTagging but when i add it to TestLanguageIdentifier class i get the same error java.lang.UnsatisfiedLinkError: also when i use libfreeling_javaAPI.jnilib i get another error libfreeling_javaAPI.jnilib: invalid ELF header (Possible cause: endianness mismatch) so please can u tell me which lib we need in class TestLanguageIdentifier ? off record if there is a problem i think it is here edu.upc.freeling.LangIdent

**Comment by ziodave** [comment]
You need the library for your o/s (i.e. "/usr/local/lib/libfreeling_javaAPI.so").

But you cannot load the same library more than once, hence the second test failure.

Your options:
1. load the library only once for the whole test suite,
2. execute a test at a time (not in the same context loader),
3. skip testing at this stage.

The preferred way should be 1. but, since the first test is working, I believe you can skip tests for now and see that the engine is working Stanbol.
